Fix: Add property bindings to playground-code-editor's value
google/playground-elements pull request #214
Opened 2021-09-24 10:35 UTC by Matsuuu

Fixes #213 

Do you see a reason why we wouldn't want to have a property binding on the value field? We have it in our `updated` -method's switch cases so it would make sense to have it as a lit property.

There's the comment on the private value field, but the property would bind to the public getter/setter.

From my testing I didn't see stuff break, and the tests run fine, so I think this is just a missing binding and will fix the case

2021-09-25 16:47 UTC, aomarks approved these changes
Cool, I think this makes sense. Adding `@property` here has 2 practical effects:

1. It will be possible to set the value by updating the `value` HTML attribute, whereas previously you could only use the property. Seems like it might be unusual to do this, but I don't see why not I guess? It would let you put some code in an editor from declarative HTML.

2. If `value` is set before the element upgrades, it will now pass through the setter and be handled correctly. This is the main benefit of this change, I think.

The 3rd effect of calling `update` when the value changes doesn't apply here, because we already define our own getter/setter that does this (this allows us to directly set the underlying `_value` property without triggering an update for when the code is changed from within by the user typing).

2021-09-25 16:48 UTC, aomarks requested changes
Oh, would you mind updating the `CHANGELOG` file, with an entry like this:

- It is now possible to directly set the `value` of a `<playground-code-editor>` from an HTML attribute, and also before the element upgrades.

2021-09-26 14:43 UTC, Matsuuu commented
Updated the changelog.

`Seems like it might be unusual to do this, but I don't see why not I guess? `

I actually ran into this while working on a "console" window for Web Component Devtools.

I'm planning on creating a console similiar to the console in chrome devtools, and used the `playground-code-editor` as it's base since that's really the only part I need for it.

2021-09-26 16:29 UTC, aomarks commented
> I'm planning on creating a console similiar to the console in chrome devtools, and used the `playground-code-editor` as it's base since that's really the only part I need for it.

Ah, cool! This makes me glad that this library is factored out into small components :)

2021-09-26 16:33 UTC, aomarks approved these changes

2021-09-26 16:33 UTC, merged